# Generated by Django 2.0.6 on 2018-07-15 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=20)),
                ('posted_by', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=12)),
                ('description', models.TextField()),
                ('posted_at', models.DateTimeField(default=datetime.datetime(2018, 7, 15, 20, 10, 23, 549262))),
            ],
            options={
                'verbose_name_plural': 'Pets',
            },
        ),
    ]
