"""
Django settings for djangoproject project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'hh_6@rzj3yxk#edpf5ur7wui6p)^)fg3d^zh7^af&xzf+7*k(r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'pets',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangoproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

#DATABASES = {
    #'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    #}
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':'djangoproject',
        'USER':'root',
        'PASSWORD':'azorahai',
        'HOST':'localhost',
        'PORT':''
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = ( os.path.join('static'), )


PROVINCE_OPTIONS= [

                      ('', 'Select Province'),
                      ('Central', 'Central'),
                      ('Copperbelt', 'Copperbelt'),
                      ('Lusaka', 'Lusaka'),
                      ('Southern', 'Southern'),
                      ('Luapula', 'Luapula'),
                      ('Northern', 'Northern'),
                      ('Eastern', 'Eastern'),
                      ('Western', 'Western'),
                      ('North Western', 'North Western'),
                      ('Muchinga', 'Muchinga'),
                    ]

TOWN_OPTIONS = (
         
                        ('Copperbelt', (
                                     ('Chambeshi', 'Chambeshi'),
                                     ('Chililabombwe', 'Chililabombwe'),
                                     ('Chingola', 'Chingola'),
                                     ('Kitwe', 'Kitwe'),
                                     ('Ndola', 'Ndola'),
                                     ('Mufulira', 'Mufulira'),
                                     ('Kalulushi', 'Kalulushi'),
                                     ('Masaiti', 'Masaiti'),
                                     ('Lufwanyama', 'Lufwanyama'),
                                 )
                        ),

                        ('Lusaka', (
                                ('Kafue', 'Kafue'),
                                ('Lusaka', 'Lusaka'),
                                ('Chilanga', 'Chilanga'),
                                ('Luangwa', 'Luangwa'),
                             )
                        ),

                        ('Central', (
                                ('Kabwe', 'Kabwe'),
                                ('Kapiri Mposhi', 'Kapiri Mposhi'),
                                ('Mkushi', 'Mkushi'),
                                ('Chirundu', 'Chirundu'),
                                ('Mumbwa', 'Mumbwa'),
                                ('Serenje', 'Serenje'),
                             )
                        ),

                        ('Southern', (
                                ('Siavonga', 'Siavonga'),
                                ('Mazabuka', 'Mazabuka'),
                                ('Livingstone', 'Livingstone'),
                                ('Kalomo', 'Kalomo'),
                                ('Maamba', 'Maamba'),
                                ('Chirundu', 'Chirundu'),
                                ('Zimba', 'Zimba'),
                                ('Monze', 'Monze'),
                                ('Namwala', 'Namwala'),
                                ('Pemba', 'Pemba'),
                             )
                        ),


                        ('North Western', (
                                ('Solwezi', 'Solwezi'),
                                ('Mwinilunga', 'Mwinilunga'),
                                ('Kansanshi', 'Kansanshi'),
                                ('Chavuma', 'Chavuma'),
                                ('Mufumbwe', 'Mufumbwe'),
                                ('Lumwana', 'Lumwana'),
                                ('Kabompo', 'Kabompo'),
                                ('Zambezi', 'Zambezi'),
                                ('Mutanda', 'Mutanda'),
                             )
                        ),


                        ('Eastern', (
                                ('Chipata', 'Chipata'),
                                ('Lundazi', 'Lundazi'),
                                ('Katete', 'Katete'),
                                ('Chadiza', 'Chadiza'),
                                ('Petauke', 'Petauke'),
                                ('Nyimba', 'Nyimba'),
                             )
                        ),


                        ('Luapula', (
                                ('Mansa', 'Mansa'),
                                ('Nchelenge', 'Nchelenge'),
                                ('Samfya', 'Samfya'),
                                ('Kashikishi', 'Kashikishi'),
                                ('Mbereshi', 'Mbereshi'),
                                ('Kataba', 'Kataba'),
                                ('Kazembe', 'Kazembe'),
                             )
                        ),

                        ('Northern', (
                                ('Kasama', 'Kasama'),
                                ('Mbala', 'Mbala'),
                                ('Luwingu', 'Luwingu'),
                                ('Mporkoso', 'Mporokoso'),
                                ('Mpulungu', 'Mpulungu'),
                             )
                        ),

                        ('Muchinga', (
                                ('Nakonde', 'Nakonde'),
                                ('Isoka', 'Isoka'),
                                ('Mpika', 'Mpika'),
                                ('Chinsali', 'Chinsali'),
                                ('Mafinga', 'Mafinga'),
                                ('Chama', 'Chama'),
                             )
                        ),


                        ('Western', (
                                ('Kaoma', 'Kaoma'),
                                ('Kalabo', 'Kalabo'),
                                ('Mongu', 'Mongu'),
                                ('Mulobezi', 'Mulobezi'),
                                ('Lukulu', 'Lukulu'),
                                ('Sesheke', 'Sesheke'),
                             )
                        ),




                )

